#!/bin/sh

set -e

PATH="/usr/local/bin:$PATH"

script_dir=$(dirname "$0")
cd "${script_dir}/../External/libgit2"

if [ -d "build" ]; then
    rm -rf "build"
fi

mkdir build
cd build

cmake -DTHREADSAFE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=OFF -DUSE_SSH:BOOL=OFF -DBUILD_CLAR:BOOL=OFF ..
cmake --build .

product="libgit2.a"
install_path="../../${product}"
if [ "${product}" -nt "${install_path}" ]; then
    cp -v "${product}" "${install_path}"
fi
